In [21]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\nasir\appdata\roaming\python\python312\site-packages (2.2.0)
Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\nasir\appdata\roaming\python\python312\site-packages (from pandas) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nasir\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\nasir\appdata\roaming\python\python312\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nasir\appdata\roaming\python\python312\site-packages (from pandas) (2023.4)
Requirement already satisfied: six>=1.5 in c:\users\nasir\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
import pandas as pd

In [23]:
file_location =r"C:\Users\nasir\OneDrive\Desktop\SOS -CS18\Sample_data\survey_results_public-2022.csv"
df=pd.read_csv(file_location)

In [24]:
df

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73263,73264,I am a developer by profession,"Employed, full-time",Fully remote,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy,8,5,"Developer, back-end",100 to 499 employees,I have some influence,Visit developer communities like Stack Overflo...,Nigeria,USD\tUnited States dollar,60000.0,Yearly,Bash/Shell;Dart;JavaScript;PHP;Python;SQL;Type...,Bash/Shell;Go;JavaScript;Python;SQL;TypeScript,Elasticsearch;MySQL;PostgreSQL;Redis,MySQL;PostgreSQL;Redis,AWS;DigitalOcean;Google Cloud,AWS;DigitalOcean;Google Cloud,Express;FastAPI;Node.js,Express;FastAPI;Node.js,Flutter,NaN,Docker;Homebrew;Kubernetes;npm,Docker;Homebrew;Kubernetes;npm,IPython/Jupyter;Sublime Text;Vim;Visual Studio...,Sublime Text;Vim;Visual Studio Code,macOS,Linux-based;macOS,Git,Code editor;Command-line,NaN,NaN,Jira Work Management,Jira Work Management,Slack;Zoom,Slack;Zoom,Very favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,African,None of the above,None of the above,Yes,Independent contributor,5.0,Agree,Disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Never,Never,Never,30-60 minutes a day,Less than 15 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Easy,NaN
73264,73265,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;Udacity,6,5,Data scientist or machine learning specialist,I don’t know,I have little or no influence,Other (please specify):;Ask developers I know/...,United States of America,USD\tUnited States dollar,107000.0,Yearly,Bash/Shell;HTML/CSS;JavaScript;Python;SQL,HTML/CSS;JavaScript;Python,Elasticsearch;MongoDB;Oracle;SQLite,Elasticsearch;Neo4j;SQLite,NaN,NaN,FastAPI;Flask;React.js,FastAPI;React.js,Keras;NumPy;Pandas;Scikit-learn;TensorFlow;Tor...,NumPy;Pandas;Torch/PyTorch;Hugging Face Transf...,NaN,NaN,IPython/Jupyter;Notepad++;Spyder;Vim;Visual St...,Notepad++;Spyder;Vim;Visual Studio Code,Linux-based;Windows,Linux-based;Windows,Git,Code editor;Command-line,NaN,NaN,NaN,NaN,Rocketchat,NaN,Unsure,Stack Overflow,Daily or almost daily,Not sure/can't remember,NaN,Neutral,25-34 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,Yes,Independent contributor,6.0,Agree,Agree,Neither agree nor disagree,Disagree,Disagree,Agree,Agree,1-2 times a week,6-10 times a week,10+ times a week,15-30 minutes a day,60-120 minutes a day,Very long,None of these,No,Yes,Yes,Too long,Easy,NaN
73265,73266,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Programming Games;Stac...,Udemy;Codecademy;Pluralsight;edX,42,33,"Developer, full-stack;Developer, desktop or en...",20 to 99 employees,I have a great deal of influence,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,NaN,NaN,HTML/CSS;JavaScript;PHP;Python;SQL,C#;HTML/CSS;JavaScript;PHP;Python;SQL,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,Managed Hosting;Microsoft Azure;VMware,Firebase;Linode;Managed Hosting;Microsoft Azur...,ASP.NET;React.js,ASP.NET;ASP.NET Core ;Blazor;Laravel;Next.js;R...,.NET;Pandas;React Native,.NET;Cordova;Ionic;Pandas;React Native;Xamarin,npm,npm;Unreal Engine,Spyder;Visual Studio;Visual Studio Code,Spyder;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Microsoft Lists,Microsoft Lists,Microsoft Teams;Zoom,Microsoft Teams;Zoom,Very unfavorable,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"Yes, somewhat",55-64 years old,Man,No,Straight / Heterosexual,Multiracial,None of the above,None of the above,Yes,Independent contributor,42.0,Disagree,Neither agree nor disagree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Never,Never,Never,30-60 minutes a day,60-120 minutes a day,Just right,None of these,No,No,No,Appropriate in length,Easy,NaN
73266,73267,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training,NaN,NaN,50,31,"Developer, front-end;Developer, desktop or ent...",10 to 19 employees,I have a great deal of influence,Start a free trial;Visit developer communities...,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,58500.0,Yearly,C#;Delphi;VBA,Delphi,Microsoft SQL Server;MongoDB;Oracle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"RAD Studio (Delphi, C++ Builder);Visual Studio","RAD Studio (Delphi, C++ Builder);Visual Studio",Windows,Windows,SVN,Dedicated version control GUI application,NaN,NaN,NaN,NaN,Zoom,Zoom,Indifferent,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",55-64 years old,Man,No,Straight / Heterosexual,European,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
73267,73268,"I used to be a developer by profession, but no...","Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Udemy;Pluralsight,16,5,"Developer, front-end;Engineer, data;Engineer, ...",NaN,NaN,Start a free trial;Visit developer communities...,Canada,NaN,NaN,NaN,C#;JavaScript;Lua;PowerShell;SQL;TypeScript,PowerShell;Rust;TypeScript,Microsoft SQL Server;Neo4j;Redis,Neo4j;Redis,Microsoft Azure,AWS;Google Cloud;Microsoft Azure;OpenStack,ASP.NET Core ;Blazor;Node.js;React.js;Svelte,ASP.NET Core ;Node.js;Svelte,Apache Kafka;Apache Spark,NaN,Docker;Kubernetes;npm;Pulumi;Terraform,Docker;Kubernetes;npm;Pulumi;Terraform,Visual Studio;Visual Studio Code,Neovim;Visual Studio Code,Linux-based;Windows,Linux-based;Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Confluence;Jira Work Management;Trello;Wrike,NaN,Microsoft Teams;Slack;Zoom,Slack;Zoom,Favorable,Collectives on Stack Overflow;Stack Overflow;S...,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",25-34 years old,Man,No,Straight / Heterosexual,"Or, in your own words:",None of the above,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN

In [25]:
#give the information about no. of rows and column
df.shape

(73268, 79)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73268 entries, 0 to 73267
Data columns (total 79 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ResponseId                      73268 non-null  int64
 1   MainBranch                      73268 non-null  object
 2   Employment                      71709 non-null  object
 3   RemoteWork                      58958 non-null  object
 4   CodingActivities                58899 non-null  object
 5   EdLevel                         71571 non-null  object
 6   LearnCode                       71580 non-null  object
 7   LearnCodeOnline                 50685 non-null  object
 8   LearnCodeCoursesCert            29389 non-null  object
 9   YearsCode                       71331 non-null  object
 10  YearsCodePro                    51833 non-null  object
 11  DevType                         61302 non-null  object
 12  OrgSize                         51039 non-null  object
 13  PurchaseInfluence               50969 non-null  object
 14  BuyNewTool                      67963 non-null  object
 15  Country                         71771 non-null  object
 16  Currency                        51264 non-null  object
 17  CompTotal                       38422 non-null  float64
 18  CompFreq                        44425 non-null  object
 19  LanguageHaveWorkedWith          70975 non-null  object
 20  LanguageWantToWorkWith          67027 non-null  object
 21  DatabaseHaveWorkedWith          60121 non-null  object
 22  DatabaseWantToWorkWith          51014 non-null  object
 23  PlatformHaveWorkedWith          49924 non-null  object
 24  PlatformWantToWorkWith          40415 non-null  object
 25  WebframeHaveWorkedWith          53544 non-null  object
 26  WebframeWantToWorkWith          46122 non-null  object
 27  MiscTechHaveWorkedWith          44992 non-null  object
 28  MiscTechWantToWorkWith          36810 non-null  object
 29  ToolsTechHaveWorkedWith         54171 non-null  object
 30  ToolsTechWantToWorkWith         46566 non-null  object
 31  NEWCollabToolsHaveWorkedWith    70347 non-null  object
 32  NEWCollabToolsWantToWorkWith    64108 non-null  object
 33  OpSysProfessional use           65503 non-null  object
 34  OpSysPersonal use               70963 non-null  object
 35  VersionControlSystem            71379 non-null  object
 36  VCInteraction                   68156 non-null  object
 37  VCHostingPersonal use           0 non-null      float64
 38  VCHostingProfessional use       0 non-null      float64
 39  OfficeStackAsyncHaveWorkedWith  46223 non-null  object
 40  OfficeStackAsyncWantToWorkWith  32072 non-null  object
 41  OfficeStackSyncHaveWorkedWith   62128 non-null  object
 42  OfficeStackSyncWantToWorkWith   47688 non-null  object
 43  Blockchain                      71071 non-null  object
 44  NEWSOSites                      71365 non-null  object
 45  SOVisitFreq                     70961 non-null  object
 46  SOAccount                       71572 non-null  object
 47  SOPartFreq                      58229 non-null  object
 48  SOComm                          71408 non-null  object
 49  Age                             70946 non-null  object
 50  Gender                          70853 non-null  object
 51  Trans                           70315 non-null  object
 52  Sexuality                       66565 non-null  object
 53  Ethnicity                       69474 non-null  object
 54  Accessibility                   67244 non-null  object
 55  MentalHealth                    66447 non-null  object
 56  TBranch                         52670 non-null  object
 57  ICorPM                          36283 non-null  object
 58  WorkExp                         36769 non-null  float64
 59  Knowledge_1                     35804 non-null  object
 60  Knowledge_2                     34973 non-null  object
 61  Knowledge_3                     35133 non-null  object
 62  Knowledge_4                     35097 non-null  object
 63  Knowledge_5                     35014 non-null  object
 64  Knowledge_6                     34991 non-null  object
 65  Knowledge_7                     34977 non-null  object
 66  Frequency_1                     35371 non-null  object
 67  Frequency_2                     35344 non-null  object
 68  Frequency_3                     34515 non-null  object
 69  TimeSearching                   36198 non-null  object
 70  TimeAnswering                   36022 non-null  object
 71  Onboarding                      35679 non-null  object
 72  ProfessionalTech                34906 non-null  object
 73  TrueFalse_1                     35819 non-null  object
 74  TrueFalse_2                     35715 non-null  object
 75  TrueFalse_3                     35749 non-null  object
 76  SurveyLength                    70444 non-null  object
 77  SurveyEase                      70508 non-null  object
 78  ConvertedCompYearly             38071 non-null  float64
dtypes: float64(5), int64(1), object(73)
memory usage: 44.2+ MB

In [27]:
#used for print dispay 84 the column and 84 rows
pd.set_option('display.max_column', 84)    
pd.set_option('display.max_row', 84)

In [28]:
#used for display what is the meaning of column 
schema_df=pd.read_csv(r"C:\Users\nasir\OneDrive\Desktop\SOS -CS18\Sample_data\survey_results_schema_2019.csv")

In [29]:
schema_df

          Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

In [30]:
#display only first 10 rows
df.head(10)
#dispaly only last 10 rows
df.tail(10)

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
73258,73259,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Stack Overflow;Video-based Online Courses;Onli...,Coursera;Udemy,5,1,"Developer, back-end",100 to 499 employees,I have some influence,Start a free trial;Ask developers I know/work ...,India,INR\tIndian rupee,3200000.0,Yearly,Go;Java;SQL,JavaScript;TypeScript,MongoDB;MySQL,MySQL;Redis,AWS,Google Cloud,NaN,NaN,Apache Kafka;Spring,NaN,Docker;Homebrew;Kubernetes;npm,Kubernetes,Eclipse;GoLand;Vim;Visual Studio Code,GoLand;Vim;Visual Studio Code,macOS,Linux-based;Windows,Git,Command-line,NaN,NaN,Notion,NaN,Slack;Zoom,NaN,Very favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",18-24 years old,Man,No,Straight / Heterosexual,Asian,NaN,None of the above,Yes,Independent contributor,1.0,Strongly agree,Disagree,Strongly agree,Agree,Neither agree nor disagree,Agree,Agree,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Neither easy nor difficult,NaN
73259,73260,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Other (please specify):,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,6,2,"Developer, back-end",10 to 19 employees,I have little or no influence,Start a free trial;Ask developers I know/work ...,Poland,PLN\tPolish zloty,8000.0,Monthly,Elixir,Elixir,PostgreSQL,PostgreSQL,AWS;Heroku,AWS,jQuery;Phoenix,Phoenix,React Native,NaN,Docker;Kubernetes,Docker;Kubernetes,Visual Studio Code,Visual Studio Code,macOS,Windows;Windows Subsystem for Linux (WSL),Git,Code editor;Command-line,NaN,NaN,ClickUp;Jira Work Management,Jira Work Management,Microsoft Teams;Slack,Slack,Unsure,Stack Overflow,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",25-34 years old,Man,No,Straight / Heterosexual,White;European,None of the above,None of the above,Yes,Independent contributor,2.0,Agree,Disagree,Agree,Strongly agree,Strongly agree,Neither agree nor disagree,Strongly agree,Never,1-2 times a week,NaN,15-30 minutes a day,Less than 15 minutes a day,Somewhat short,DevOps function;Continuous integration (CI) an...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,NaN
73260,73261,I am a developer by profession,"Employed, full-time;Student, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",NaN,NaN,8,NaN,"Developer, back-end;Student",NaN,NaN,Visit developer communities like Stack Overflo...,Belgium,NaN,NaN,NaN,C#,C#,Microsoft SQL Server,Microsoft SQL Server,Microsoft Azure,Microsoft Azure,ASP.NET;ASP.NET Core,ASP.NET Core ;Blazor,.NET,.NET,Docker,Docker;Kubernetes,Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Notion,ClickUp,Microsoft Teams;Zoom,Microsoft Teams,Unfavorable,Stack Overflow,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",18-24 years old,Man,No,Straight / Heterosexual,European,None of the above,I have a concentration and/or memory disorder ...,Yes,Independent contributor,3.0,Neither agree nor disagree,Agree,Agree,Agree,Neither agree nor disagree,Agree,Strongly agree,Never,1-2 times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Very long,DevOps function;Developer portal or other cent...,No,No,Yes,Appropriate in length,Easy,NaN
73261,73262,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Programming Game...,Udemy;Codecademy;Pluralsight,9,2,"Developer, full-stack","10,000 or more employees",I have little or no influence,Start a free trial;Visit developer communities...,France,EUR European Euro,36000.0,Yearly,Bash/Shell;HTML/CSS;Java;JavaScript;Python;SQL...,Bash/Shell;HTML/CSS;Java;JavaScript;Kotlin;Pyt...,MySQL,Elasticsearch;MongoDB;MySQL;Redis,Microsoft Azure,Microsoft Azure,Angular;Angular.js;Drupal;Node.js,Angular;Node.js,Spring,Spring,Docker;npm,Ansible;Chef;Docker;Kubernetes;npm;Terraform;Yarn,Eclipse;Notepad++;Visual Studio Code,IntelliJ;Visual Studio Code,Linux-based;Windows;Windows Subsystem for Linu...,Windows;Windows Subsystem for Linux (WSL),Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management,NaN,Microsoft Teams,Microsoft Teams,Unfavorable,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not really",18-24 years old,Man,No,NaN,European,None of the above,None of the above,Yes,Independent contributor,2.0,Agree,Agree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,1-2 times a week,3-5 times a week,1-2 times a week,15-30 minutes a day,15-30 minutes a day,Somewhat long,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Easy,NaN
73262,73263,I am learning to code,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Written Tutorials;Stac...,NaN,4,NaN,"Developer, front-end;Student",NaN,NaN,NaN,Germany,NaN,NaN,NaN,Assembly;C;C++;Java;TypeScript,C++;Java,NaN,NaN,NaN,NaN,Node.js,NaN,NaN,NaN,npm,NaN,Eclipse;Visual Studio Code,Android Studio;Visual Studio Code,NaN,Linux-based;Windows,Git,Command-line,NaN,NaN,Notion,Notion,Slack;Zoom,NaN,Unsure,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,"No, not really",18-24 years old,Man,No,Straight / Heterosexual,European,None of the above,"I have a mood or emotional disorder (e.g., dep...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
73263,73264,I am a developer by profession,"Employed, full-time",Fully remote,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy,8,5,"Developer, back-end",100 to 499 employees,I have some influence,Visit developer communities like Stack Overflo...,Nigeria,USD\tUnited States dollar,60000.0,Yearly,Bash/Shell;Dart;JavaScript;PHP;Python;SQL;Type...,Bash/Shell;Go;JavaScript;Python;SQL;TypeScript,Elasticsearch;MySQL;PostgreSQL;Redis,MySQL;PostgreSQL;Redis,AWS;DigitalOcean;Google Cloud,AWS;DigitalOcean;Google Cloud,Express;FastAPI;Node.js,Express;FastAPI;Node.js,Flutter,NaN,Docker;Homebrew;Kubernetes;npm,Docker;Homebrew;Kubernetes;npm,IPython/Jupyter;Sublime Text;Vim;Visual Studio...,Sublime Text;Vim;Visual Studio Code,macOS,Linux-based;macOS,Git,Code editor;Command-line,NaN,NaN,Jira Work Management,Jira Work Management,Slack;Zoom,Slack;Zoom,Very favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,African,None of the above,None of the above,Yes,Independent contributor,5.0,Agree,Disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Never,Never,Never,30-60 minutes a day,Less than 15 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Easy,NaN
73264,73265,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;Udacity,6,5,Data scientist or machine learning specialist,I don’t know,I have little or no influence,Other (please specify):;Ask developers I know/...,United States of America,USD\tUnited States dollar,107000.0,Yearly,Bash/Shell;HTML/CSS;JavaScript;Python;SQL,HTML/CSS;JavaScript;Python,Elasticsearch;MongoDB;Oracle;SQLite,Elasticsearch;Neo4j;SQLite,NaN,NaN,FastAPI;Flask;React.js,FastAPI;React.js,Keras;NumPy;Pandas;Scikit-learn;TensorFlow;Tor...,NumPy;Pandas;Torch/PyTorch;Hugging Face Transf...,NaN,NaN,IPython/Jupyter;Notepad++;Spyder;Vim;Visual St...,Notepad++;Spyder;Vim;Visual Studio Code,Linux-based;Windows,Linux-based;Windows,Git,Code editor;Command-line,NaN,NaN,NaN,NaN,Rocketchat,NaN,Unsure,Stack Overflow,Daily or almost daily,Not sure/can't remember,NaN,Neutral,25-34 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,Yes,Independent contributor,6.0,Agree,Agree,Neither agree nor disagree,Disagree,Disagree,Agree,Agree,1-2 times a week,6-10 times a week,10+ times a week,15-30 minutes a day,60-120 minutes a day,Very long,None of these,No,Yes,Yes,Too long,Easy,NaN
73265,73266,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Programming Games;Stac...,Udemy;Codecademy;Pluralsight;edX,42,33,"Developer, full-stack;Developer, desktop or en...",20 to 99 employees,I have a great deal of influence,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,NaN,NaN,HTML/CSS;JavaScript;PHP;Python;SQL,C#;HTML/CSS;JavaScript;PHP;Python;SQL,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,Managed Hosting;Microsoft Azure;VMware,Firebase;Linode;Managed Hosting;Microsoft Azur...,ASP.NET;React.js,ASP.NET;ASP.NET Core ;Blazor;Laravel;Next.js;R...,.NET;Pandas;React Native,.NET;Cordova;Ionic;Pandas;React Native;Xamarin,npm,npm;Unreal Engine,Spyder;Visual Studio;Visual Studio Code,Spyder;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Microsoft Lists,Microsoft Lists,Microsoft Teams;Zoom,Microsoft Teams;Zoom,Very unfavorable,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"Yes, somewhat",55-64 years old,Man,No,Straight / Heterosexual,Multiracial,None of the above,None of the above,Yes,Independent contributor,42.0,Disagree,Neither agree nor disagree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Never,Never,Never,30-60 minutes a day,60-120 minutes a day,Just right,None of these,No,No,No,Appropriate in length,Easy,NaN
73266,73267,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training,NaN,NaN,50,31,"Developer, front-end;Developer, desktop or ent...",10 to 19 employees,I have a great deal of influence,Start a free trial;Visit developer communities...,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,58500.0,Yearly,C#;Delphi;VBA,Delphi,Microsoft SQL Server;MongoDB;Oracle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"RAD Studio (Delphi, C++ Builder);Visual Studio","RAD Studio (Delphi, C++ Builder);Visual Studio",Windows,Windows,SVN,Dedicated version control GUI application,NaN,NaN,NaN,NaN,Zoom,Zoom,Indifferent,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",55-64 years old,Man,No,Straight / Heterosexual,European,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
73267,73268,"I used to be a developer by profession, but no...","Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Udemy;Pluralsight,16,5,"Developer, front-end;Engineer, data;Engineer, ...",NaN,NaN,Start a free trial;Visit developer communities...,Canada,NaN,NaN,NaN,C#;JavaScript;Lua;PowerShell;SQL;TypeScript,PowerShell;Rust;TypeScript,Microsoft SQL Server;Neo4j;Redis,Neo4j;Redis,Microsoft Azure,AWS;Google Cloud;Microsoft Azure;OpenStack,ASP.NET Core ;Blazor;Node.js;React.js;Svelte,ASP.NET Core ;Node.js;Svelte,Apache Kafka;Apache Spark,NaN,Docker;Kubernetes;npm;Pulumi;Terraform,Docker;Kubernetes;npm;Pulumi;Terraform,Visual Studio;Visual Studio Code,Neovim;Visual Studio Code,Linux-based;Windows,Linux-based;Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Confluence;Jira Work Management;Trello;Wrike,NaN,Microsoft Teams;Slack;Zoom,Slack;Zoom,Favorable,Collectives on Stack Overflow;Stack Overflow;S...,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",25-34 years old,Man,No,Straight / Heterosexual,"Or, in your own words:",None of the above,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN

In [31]:
# Dictionary 
people= { "First":["Nasiruddin","Rohit","Sahil","sandipan"],
        "last":["Kabir","ahammed","Ahamed","Mandal"],
        "Email":["nasir@gamil.com","rohit@gamilcom","sahil@gamil.com","sandipa@gmail.com"]
}

In [32]:
import pandas as pd

In [33]:
df2=pd.DataFrame(people)

In [34]:
df2

        First     last              Email
0  Nasiruddin    Kabir    nasir@gamil.com
1       Rohit  ahammed     rohit@gamilcom
2       Sahil   Ahamed    sahil@gamil.com
3    sandipan   Mandal  sandipa@gmail.com

In [35]:
#access a column
df2['Email']

0      nasir@gamil.com
1       rohit@gamilcom
2      sahil@gamil.com
3    sandipa@gmail.com
Name: Email, dtype: object

In [36]:
#access a column
df2.Email

0      nasir@gamil.com
1       rohit@gamilcom
2      sahil@gamil.com
3    sandipa@gmail.com
Name: Email, dtype: object

In [37]:
df2[['last','Email']]

      last              Email
0    Kabir    nasir@gamil.com
1  ahammed     rohit@gamilcom
2   Ahamed    sahil@gamil.com
3   Mandal  sandipa@gmail.com

In [38]:
#Printing the column   it is a list
df2.columns

Index(['First', 'last', 'Email'], dtype='object')

In [39]:
#printing row we used loc or iloc
df2.iloc[0]

First         Nasiruddin
last               Kabir
Email    nasir@gamil.com
Name: 0, dtype: object

In [40]:
#C

df2.iloc[[0,1],2]
#[0,1] repesent first 2 rows and 2 repesent the column 2 here it is "Email"

0    nasir@gamil.com
1     rohit@gamilcom
Name: Email, dtype: object

In [41]:
#printing a column with row using loc
df2.loc[[0,1],['Email','last']]

             Email     last
0  nasir@gamil.com    Kabir
1   rohit@gamilcom  ahammed

In [42]:
#for counting different type of thing in 'LearnCodeOnline' column
df['LearnCodeOnline'].value_counts()

LearnCodeOnline
Technical documentation;Blogs;Written Tutorials;Stack Overflow                                                                                                                                         715
Technical documentation;Blogs;Written Tutorials;Stack Overflow;Online forum                                                                                                                            706
Technical documentation;Blogs;Stack Overflow                                                                                                                                                           589
Technical documentation;Blogs;Written Tutorials;Stack Overflow;Online books;Online forum                                                                                                               530
Technical documentation;Blogs;Written Tutorials;Stack Overflow;Online books                                                                                                                            447
                                                                                                                                                                                                      ...
Technical documentation;Blogs;Stack Overflow;Online books;Online challenges (e.g., daily or weekly coding challenges);Online forum;Coding sessions (live or recorded);Other (Please specify):            1
Technical documentation;Blogs;Programming Games;Written Tutorials;Stack Overflow;Auditory material (e.g., podcasts)                                                                                      1
Technical documentation;Written Tutorials;Stack Overflow;Written-based Online Courses;Interactive tutorial;Coding sessions (live or recorded);Certification videos                                       1
Technical documentation;Blogs;Video-based Online Courses;Online forum;Auditory material (e.g., podcasts);Interactive tutorial;Coding sessions (live or recorded)                                         1
Technical documentation;Programming Games;Stack Overflow;Online books;Video-based Online Courses;How-to videos;Written-based Online Courses;Coding sessions (live or recorded);Certification videos      1
Name: count, Length: 7192, dtype: int64

In [43]:
#change a column to index but it not modified the data frame
df2.set_index('last')

              First              Email
last
Kabir    Nasiruddin    nasir@gamil.com
ahammed       Rohit     rohit@gamilcom
Ahamed        Sahil    sahil@gamil.com
Mandal     sandipan  sandipa@gmail.com

In [44]:
#to modified the index
df2.set_index('last', inplace=True)
#we also apply another method to do this thing: 
                 # df=pd.read_csv('filename',index_col='column name')

In [45]:
df2

              First              Email
last
Kabir    Nasiruddin    nasir@gamil.com
ahammed       Rohit     rohit@gamilcom
Ahamed        Sahil    sahil@gamil.com
Mandal     sandipan  sandipa@gmail.com

In [46]:
# To set the index in alphabatically order 
df2.sort_index(ascending=True,inplace=True)

In [47]:
df2

              First              Email
last
Ahamed        Sahil    sahil@gamil.com
Kabir    Nasiruddin    nasir@gamil.com
Mandal     sandipan  sandipa@gmail.com
ahammed       Rohit     rohit@gamilcom

In [48]:
friend={"Frist":["Anawar","Hafiz","Arnab","Shartak"],
         "last":["Hossain","Hossain","Ghosh","Pal"],
           "Age":["20","20.5","19","19.5"],
          "Exam":["50%","99%","20%","5%"] }

In [49]:
d3f=pd.DataFrame(friend)

In [50]:
d3f

     Frist     last   Age Exam
0   Anawar  Hossain    20  50%
1    Hafiz  Hossain  20.5  99%
2    Arnab    Ghosh    19  20%
3  Shartak      Pal  19.5   5%

In [51]:
d3f['last']=='Hossain'

0     True
1     True
2    False
3    False
Name: last, dtype: bool

In [52]:
#To filter something
filt=(d3f['last']=='Hossain')

In [53]:
#which gives true they are filter out---->PASSING BOOL
d3f[filt]

    Frist     last   Age Exam
0  Anawar  Hossain    20  50%
1   Hafiz  Hossain  20.5  99%

In [54]:
#passing multiple filter --------> USE OR ,AND
fil=(d3f['last']=='Hossain') & ( d3f['Frist']=='Anawar')

In [55]:
d3f[fil]

    Frist     last Age Exam
0  Anawar  Hossain  20  50%

In [56]:
df4=pd.read_csv(r"C:\Users\nasir\OneDrive\Desktop\SOS -CS18\Sample_data\survey_results_public_2019.csv")

In [57]:
df4

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,...,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,...,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,...,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,...,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [58]:
#filter out by country name 
countries=['United States','India','Germany','Canada']
fit=df4['Country'].isin(countries)

In [59]:
#checking is the string is present on not
df4['LanguageWorkedWith'].str.contains('Python',na=False)

0         True
1         True
2        False
3         True
4         True
         ...
88878    False
88879    False
88880    False
88881    False
88882    False
Name: LanguageWorkedWith, Length: 88883, dtype: bool

In [60]:
d3f.columns=["Frist Name","Last Name","Age","Selection Probality"]

In [61]:
d3f

  Frist Name Last Name   Age Selection Probality
0     Anawar   Hossain    20                 50%
1      Hafiz   Hossain  20.5                 99%
2      Arnab     Ghosh    19                 20%
3    Shartak       Pal  19.5                  5%

In [62]:
#To change all the column name into upper case
d3f.columns = [x.upper() for x in d3f.columns]
d3f

  FRIST NAME LAST NAME   AGE SELECTION PROBALITY
0     Anawar   Hossain    20                 50%
1      Hafiz   Hossain  20.5                 99%
2      Arnab     Ghosh    19                 20%
3    Shartak       Pal  19.5                  5%

In [63]:
#to replace something
d3f.columns= d3f.columns.str.replace(' ','_')

In [64]:
d3f

  FRIST_NAME LAST_NAME   AGE SELECTION_PROBALITY
0     Anawar   Hossain    20                 50%
1      Hafiz   Hossain  20.5                 99%
2      Arnab     Ghosh    19                 20%
3    Shartak       Pal  19.5                  5%

In [65]:
#To update a full row by scicific data 
d3f.loc[1]=['Hafiz','Ali','20','98.9%']

In [66]:
d3f

  FRIST_NAME LAST_NAME   AGE SELECTION_PROBALITY
0     Anawar   Hossain    20                 50%
1      Hafiz       Ali    20               98.9%
2      Arnab     Ghosh    19                 20%
3    Shartak       Pal  19.5                  5%

In [67]:
#To update a element / 2 element of row [1] is the row
d3f.loc[[1],['Last Name','Age']]=['Ahammed','20.5']

C:\Users\nasir\AppData\Local\Temp\ipykernel_11884\722850483.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Ahammed' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  d3f.loc[[1],['Last Name','Age']]=['Ahammed','20.5']
C:\Users\nasir\AppData\Local\Temp\ipykernel_11884\722850483.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '20.5' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  d3f.loc[[1],['Last Name','Age']]=['Ahammed','20.5']

In [68]:
d3f

  FRIST_NAME LAST_NAME   AGE SELECTION_PROBALITY Last Name   Age
0     Anawar   Hossain    20                 50%       NaN   NaN
1      Hafiz       Ali    20               98.9%   Ahammed  20.5
2      Arnab     Ghosh    19                 20%       NaN   NaN
3    Shartak       Pal  19.5                  5%       NaN   NaN

In [70]:
# to change a whole column into lower case
d3f['Frist_Name']=d3f['Frist'].str.lower()

KeyError: 'Frist'

In [71]:
d3f

  FRIST_NAME LAST_NAME   AGE SELECTION_PROBALITY Last Name   Age
0     Anawar   Hossain    20                 50%       NaN   NaN
1      Hafiz       Ali    20               98.9%   Ahammed  20.5
2      Arnab     Ghosh    19                 20%       NaN   NaN
3    Shartak       Pal  19.5                  5%       NaN   NaN

In [72]:
# "apply" method 
def update_email(email):
    return email.upper()
## here we apply the function to this email
df2['Email'].apply(update_email)

last
Ahamed       SAHIL@GAMIL.COM
Kabir        NASIR@GAMIL.COM
Mandal     SANDIPA@GMAIL.COM
ahammed       ROHIT@GAMILCOM
Name: Email, dtype: object

In [73]:
#in above we have apply index as lasrt name 
df2['Email'].apply(len)

last
Ahamed     15
Kabir      15
Mandal     17
ahammed    14
Name: Email, dtype: int64

In [74]:
#To apply in all the element in the data frame we use applymap
d3f.applymap(len)

C:\Users\nasir\AppData\Local\Temp\ipykernel_11884\3803962375.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  d3f.applymap(len)

TypeError: object of type 'float' has no len()

In [ ]:
#to rename a column or a element
d3f.rename(columns={"Frist":"Frist_Name"},inplace=True)
d3f

  Frist_Name Last_Name   Age Selection_Probality Last Name
0     Anawar   Hossain    20                 50%       NaN
1      Hafiz       Ali  20.5               98.9%   Ahammed
2      Arnab     Ghosh    19                 20%       NaN
3    Shartak       Pal  19.5                  5%       NaN

In [ ]:
df4['Hobbyist'].map({'Yes':'Y','No':'N'})

NameError: name 'df4' is not defined

In [75]:
d3f

  FRIST_NAME LAST_NAME   AGE SELECTION_PROBALITY Last Name   Age
0     Anawar   Hossain    20                 50%       NaN   NaN
1      Hafiz       Ali    20               98.9%   Ahammed  20.5
2      Arnab     Ghosh    19                 20%       NaN   NaN
3    Shartak       Pal  19.5                  5%       NaN   NaN

In [76]:
# To Joining the first name and last name and append in Data frame 
d3f['Full Name']=d3f['Frist Name'] + ' ' +d3f['Last Name']
d3f

KeyError: 'Frist Name'

In [77]:
d3f.rename(columns={'Frist Name':'Frist','Last Name':'Last','Full Name':'Name'},inplace=True)
d3f

  FRIST_NAME LAST_NAME   AGE SELECTION_PROBALITY     Last   Age
0     Anawar   Hossain    20                 50%      NaN   NaN
1      Hafiz       Ali    20               98.9%  Ahammed  20.5
2      Arnab     Ghosh    19                 20%      NaN   NaN
3    Shartak       Pal  19.5                  5%      NaN   NaN

In [78]:
#Drop a colummn 
d3f.drop(columns=['Frist','Last'])  # use inplace= True to replace it permanently

KeyError: "['Frist'] not found in axis"

In [79]:
# To split a string
d3f['Name'].str.split(' ')

KeyError: 'Name'

In [80]:
# TO expand a column 
d3f[["F_Name","L_Name"]]=d3f["Name"].str.split(' ',expand=True)

KeyError: 'Name'

In [81]:
d3f

  FRIST_NAME LAST_NAME   AGE SELECTION_PROBALITY     Last   Age
0     Anawar   Hossain    20                 50%      NaN   NaN
1      Hafiz       Ali    20               98.9%  Ahammed  20.5
2      Arnab     Ghosh    19                 20%      NaN   NaN
3    Shartak       Pal  19.5                  5%      NaN   NaN

In [82]:
#To append some thing a New column
new_insert={'Frist':['Nasir'],'Age':['20'] }
d_insert=pd.DataFrame(new_insert)
d3f=pd.concat([d3f,d_insert],ignore_index=True)   # we USe ignore_index=True because there are some missing data
d3f

  FRIST_NAME LAST_NAME   AGE SELECTION_PROBALITY     Last   Age  Frist
0     Anawar   Hossain    20                 50%      NaN   NaN    NaN
1      Hafiz       Ali    20               98.9%  Ahammed  20.5    NaN
2      Arnab     Ghosh    19                 20%      NaN   NaN    NaN
3    Shartak       Pal  19.5                  5%      NaN   NaN    NaN
4        NaN       NaN   NaN                 NaN      NaN    20  Nasir

In [83]:
people_4={"Frist":["Tony","steven"],
     "Last": ["Stark","Roger"]    
}
df5=pd.DataFrame(people_4)
df5

    Frist   Last
0    Tony  Stark
1  steven  Roger

In [84]:
# Concat another dataframe with d3f
d3f = pd.concat([d3f, df5], ignore_index=True)

In [85]:
d3f

  FRIST_NAME LAST_NAME   AGE SELECTION_PROBALITY     Last   Age   Frist
0     Anawar   Hossain    20                 50%      NaN   NaN     NaN
1      Hafiz       Ali    20               98.9%  Ahammed  20.5     NaN
2      Arnab     Ghosh    19                 20%      NaN   NaN     NaN
3    Shartak       Pal  19.5                  5%      NaN   NaN     NaN
4        NaN       NaN   NaN                 NaN      NaN    20   Nasir
5        NaN       NaN   NaN                 NaN    Stark   NaN    Tony
6        NaN       NaN   NaN                 NaN    Roger   NaN  steven

In [86]:
# Drop a index
d3f.drop(index=6,inplace=True)

In [87]:
d3f

  FRIST_NAME LAST_NAME   AGE SELECTION_PROBALITY     Last   Age  Frist
0     Anawar   Hossain    20                 50%      NaN   NaN    NaN
1      Hafiz       Ali    20               98.9%  Ahammed  20.5    NaN
2      Arnab     Ghosh    19                 20%      NaN   NaN    NaN
3    Shartak       Pal  19.5                  5%      NaN   NaN    NaN
4        NaN       NaN   NaN                 NaN      NaN    20  Nasir
5        NaN       NaN   NaN                 NaN    Stark   NaN   Tony

In [88]:
#Drop by condn
d3f.drop(index=d3f[d3f['Last']=='Pal'].index)

  FRIST_NAME LAST_NAME   AGE SELECTION_PROBALITY     Last   Age  Frist
0     Anawar   Hossain    20                 50%      NaN   NaN    NaN
1      Hafiz       Ali    20               98.9%  Ahammed  20.5    NaN
2      Arnab     Ghosh    19                 20%      NaN   NaN    NaN
3    Shartak       Pal  19.5                  5%      NaN   NaN    NaN
4        NaN       NaN   NaN                 NaN      NaN    20  Nasir
5        NaN       NaN   NaN                 NaN    Stark   NaN   Tony

In [89]:
#sorting
d3f.sort_values(by='Last',ascending=True)

  FRIST_NAME LAST_NAME   AGE SELECTION_PROBALITY     Last   Age  Frist
1      Hafiz       Ali    20               98.9%  Ahammed  20.5    NaN
5        NaN       NaN   NaN                 NaN    Stark   NaN   Tony
0     Anawar   Hossain    20                 50%      NaN   NaN    NaN
2      Arnab     Ghosh    19                 20%      NaN   NaN    NaN
3    Shartak       Pal  19.5                  5%      NaN   NaN    NaN
4        NaN       NaN   NaN                 NaN      NaN    20  Nasir

In [90]:
# sorting by using two condition
d3f.sort_values(by=["Last","Frist"],ascending=[True,True])    # Give more priority to the which writen frist in the list

  FRIST_NAME LAST_NAME   AGE SELECTION_PROBALITY     Last   Age  Frist
1      Hafiz       Ali    20               98.9%  Ahammed  20.5    NaN
5        NaN       NaN   NaN                 NaN    Stark   NaN   Tony
4        NaN       NaN   NaN                 NaN      NaN    20  Nasir
0     Anawar   Hossain    20                 50%      NaN   NaN    NaN
2      Arnab     Ghosh    19                 20%      NaN   NaN    NaN
3    Shartak       Pal  19.5                  5%      NaN   NaN    NaN

In [91]:
df4.sort_values(by=['ConvertedComp','Country'],ascending=[False,True],inplace=True)
df4[['Country','ConvertedComp']].head(50)

              Country  ConvertedComp
25833          Canada      2000000.0
87353         Germany      2000000.0
21895           India      2000000.0
28080           India      2000000.0
72274           India      2000000.0
77665          Mexico      2000000.0
79701     Netherlands      2000000.0
51798            Peru      2000000.0
75088       Singapore      2000000.0
32056     Switzerland      2000000.0
83866  United Kingdom      2000000.0
57      United States      2000000.0
101     United States      2000000.0
164     United States      2000000.0
434     United States      2000000.0
450     United States      2000000.0
489     United States      2000000.0
537     United States      2000000.0
767     United States      2000000.0
786     United States      2000000.0
1228    United States      2000000.0
1374    United States      2000000.0
1375    United States      2000000.0
1404    United States      2000000.0
1445    United States      2000000.0
1566    United States      2000000.0
1750    United States      2000000.0
2105    United States      2000000.0
2107    United States      2000000.0
2156    United States      2000000.0
2209    United States      2000000.0
2336    United States      2000000.0
2588    United States      2000000.0
2628    United States      2000000.0
2650    United States      2000000.0
2655    United States      2000000.0
2703    United States      2000000.0
2851    United States      2000000.0
2927    United States      2000000.0
2951    United States      2000000.0
3106    United States      2000000.0
3119    United States      2000000.0
3237    United States      2000000.0
3251    United States      2000000.0
3269    United States      2000000.0
3502    United States      2000000.0
3520    United States      2000000.0
3625    United States      2000000.0
3646    United States      2000000.0
3832    United States      2000000.0

In [92]:
# Find 10 largest value among the columns
df4['ConvertedComp'].nlargest(10)

## df.nleargest(10,'ConvertedComp')

25833    2000000.0
87353    2000000.0
21895    2000000.0
28080    2000000.0
72274    2000000.0
77665    2000000.0
79701    2000000.0
51798    2000000.0
75088    2000000.0
32056    2000000.0
Name: ConvertedComp, dtype: float64

In [93]:
# Finding mean/median/ mode
df4["ConvertedComp"].median()

57287.0

In [94]:
lis=['ConvertedComp','CompTotal','WorkWeekHrs','CodeRevHrs','Age']

In [95]:
# To define the stastic of the following columns
df4[lis].describe()

       ConvertedComp     CompTotal   WorkWeekHrs    CodeRevHrs           Age
count   5.582300e+04  5.594500e+04  64503.000000  49790.000000  79210.000000
mean    1.271107e+05  5.519014e+11     42.127197      5.084308     30.336699
std     2.841523e+05  7.331926e+13     37.287610      5.513931      9.178390
min     0.000000e+00  0.000000e+00      1.000000      0.000000      1.000000
25%     2.577750e+04  2.000000e+04     40.000000      2.000000     24.000000
50%     5.728700e+04  6.200000e+04     40.000000      4.000000     29.000000
75%     1.000000e+05  1.200000e+05     44.750000      6.000000     35.000000
max     2.000000e+06  1.000000e+16   4850.000000     99.000000     99.000000

In [96]:
#to watch no. of column contained the value
df4['ConvertedComp'].count()

55823

In [97]:
# To find the distribution of the columns
df4["Hobbyist"].value_counts()

Hobbyist
Yes    71257
No     17626
Name: count, dtype: int64

In [98]:
filt1=df4["Country"]=='India'
df4.loc[filt1]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,...,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
21895,22013,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Professional degree (JD, MD, etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,2-9 employees,Academic researcher;Data scientist or machine ...,3,26,3,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,"Write code by hand (e.g., on a whiteboard);Com...",No,Financial performance or funding status of the...,"Something else changed (education, award, medi...",USD,United States dollar,1500000.0,Weekly,2000000.0,50.0,There's no schedule or spec; I work on what se...,Inadequate access to necessary tools;Meetings;...,All or almost all the time (I'm full-time remote),Home,A little below average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Developers typically have the most influence o...,...,Assembly;Bash/Shell/PowerShell;C;C++;Java;Java...,Python;Swift,Cassandra;Microsoft SQL Server;Oracle,Cassandra,Android;Arduino;Google Cloud Platform;IBM Clou...,IBM Cloud or Watson;Windows,jQuery,NaN,TensorFlow,TensorFlow,Visual Studio;Visual Studio Code,Windows,Development,Implementing our own cryptocurrency,Useful across many domains and could change ma...,Yes,Yes,No,YouTube,Online,Screen Name,NaN,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,Yes,"Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy
28080,28243,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,2-9 employees,"Developer, back-end;Developer, full-stack;Deve...",25,9,14,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles;Interview ...,Yes,Financial performance or funding status of the...,I heard about a job opportunity (from a recrui...,USD,United States dollar,2000000.0,Yearly,2000000.0,20.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Not eno...,All or almost all the time (I'm full-time remote),Office,Far above average,"Yes, because I see value in code review",NaN,NaN,NaN,...,C++;C#;Java;JavaScript;Objective-C;Python,C;C++;C#,PostgreSQL;SQLite,SQLite,Android;AWS;iOS;MacOS;Windows,Android;Linux,NaN,NaN,Node.js;Pandas;Unity 3D,Unity 3D;Unreal Engine,Android Studio;Coda;PyCharm;Visual Studio;Visu...,MacOS,I do not use containers,NaN,An irresponsible use of resources,No,Yes,No,I don't use social media,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,60+ minutes,Yes,Multiple times per day,Yes,"No, and I don't know what those are","Yes, definitely",A lot less welcome now than last year,Tech meetups or events in your area,NaN,NaN,NaN,Straight / Heterosexual,NaN,Yes,Too short,Easy
72274,72732,"I am not primarily a developer, but I write co...",No,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",NaN,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Contributed to open source software,NaN,NaN,4,20,5,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,I am actively looking for a job,More than 4 years ago,Write any code,No,Remote work options;Opportunities for professi...,I was preparing for a job search,USD,United States dollar,80000.0,Weekly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Meetings;Time ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Not sure,...,Java;Python;SQL,NaN,MongoDB;Microsoft SQL Server;MySQL;Oracle;Post...,MySQL,Android;Windows,AWS;Docker,NaN,Angular/Angular.js;React.js,NaN,NaN,Eclipse;Notepad++;PyCharm,Windows,Testing,NaN,NaN,Yes,Yes,No,WhatsApp,Neither,NaN,2017,A few times per month or weekly,Get a sense of belonging to the developer comm...,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are",Not sure,A lot less welcome now than last year,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,Yes,Too long,Easy
16703,16793,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...",Academic researcher;Data or business analyst;D...,14,14,6,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,I am actively looking for a job,1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",Yes,Office environment or company culture;Opportun...,I heard about a job opportunity (from a recrui...,INR,Indian rupee,106673250.0,Yearly,1000000.0,50.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Non-work commitme...,It's complicated,Office,Far above average,"Yes, because I see value in code review",20.0,NaN,NaN,...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Dart;G...,Bash/Shell/PowerShell;C;C++;Go;HTML/CSS;Java;J...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Angular/Angular.js;ASP.NET;Django;Drupal;Expre...,Angular/Angular.js;ASP.NET;Django;Flask;jQuery...,Apache Spark;Flutter;Hadoop;.NET;.NET Core;Nod...,Apache Spark;Hadoop;Pandas;TensorFlow;Torch/Py...,Android Studio;Atom;Eclipse;Emacs;IntelliJ;IPy...,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,Also Yes,What?,LinkedIn,Online,Handle,2009,Multiple times per day,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per week,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, definitely",Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,27.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Neither easy nor difficult
52225,52561,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"5,000 to 9,999 employees","Developer, back-end;Developer, desktop or ente...",12,11,9,Slightly satisfied,Slightly satisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",3-4 years ago,"Write any code;Write code by hand (e.g., on a ...",No,"Languages, frameworks, and other technologies ...","Something else changed (education, award, medi...",INR,Indian rupee,2000000.0,Weekly,1000000.0,40.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Distrac...,A few days each month,Office,A little above average,"Yes, because I was told to do so",2.0,"Yes, it's part of our process",Developers and management have nearly equal in...,...,C#;JavaScript,C#;JavaScript,DynamoDB;Microsoft SQL Server;SQLite,DynamoDB;Microsoft SQL Server,AWS;Docker;Linux;Windows,AWS;Docker;Linux;Windows,Angular/Angular.js;ASP.NET;Express;React.js,Angular/Angular.js;ASP.NET;Express;React.js,.NET;.NET Core;Node.js,.NET;.NET Core;Node.js,Visual Studio;Visual Studio Code,Windows,Development;Testing;Production;Outside of work...,Not at all,Useful for immutable record keeping outside of...,No,Also Yes,Yes,YouTube,Online,UserID,2009,Daily or almost daily,Find answers to specific questions;Contribute ...,1-2 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,31.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88808,77339,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Taken an online course in programming or softw...,"1,000 to 4,999 employees",NaN,1,27,1,NaN,NaN,Somewhat confident,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Other(s):,Python;SQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,No,YouTube,Online,UserID,2019,Less than once per month or monthly,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, I've heard of them, but I am not part of a...","Yes, somewhat",Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Indu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88825,79795,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,500 to 999 employees,"Developer, QA or test",6,17,5,NaN,NaN,Somewhat confident,No,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Bash/Shell/PowerShell;Python;SQL;VBA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apache Spark;Chef;Puppet,NaN,PyCharm;Vim,Linux-based,Development;Testing;Production;Outside of work...,Not at all,NaN,No,Yes,What?,Instagram,In real life (in person),Username,2018,A few times per month or weekly,Find answers to specific questions,Less than once per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Somewhat more welcome now than last year,Tech meetups or events in your area;Courses on...,NaN,Man,No,Straight / Heterosexual,NaN,No,Too long,Difficult
88852,83862,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,Participated in a hackathon,NaN,Data or business analyst;Student,1,18,Less than 1 year,NaN,NaN,Very confident,Not sure,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Assembly;C;C++;HTML/CSS;Java;JavaScript;Object...,NaN,MySQL,DynamoDB;Elasticsearch;MongoDB,Android;AWS;Google Cloud Platform;WordPress,IBM Cloud or Watson,Laravel,Angular/Angular.js;Laravel;Vue.js,NaN,Node.js,Android Studio;Atom;IntelliJ;Komodo;NetBeans;N...,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,No,Yes,What?,Twitter,Online,UserID,2012,A few times per month or weekly,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was much faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
88853,84299,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,100 to 499 employees,"Developer, back-end;Developer, front-end;Devel...",12,25,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,HTML/CSS;Java;JavaScript;Python;Swift;TypeScript,HTML/CSS;Java;JavaScript,MongoDB;Redis;SQLite,MongoDB;Redis,NaN,NaN,Angular/Angular.js;Express;jQuery;React.js;Oth...,Express;React.js;Other(s):,Node.js,Node.js,IntelliJ;Notepad++;Visual Studio Code;Xcode,Windows,NaN,NaN,NaN,Yes,"Fortunately, someone else has that title",What?,LinkedIn,NaN,NaN,2011,A few times per month or weekly,Find answers to specific questions;Contribute ...,Less than once per week,Stack Overflow was much faster,60+ minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat more welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88864,86012,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...",100 to 499 employees,Academic researcher;Educator,5,15,NaN,NaN,NaN,Somewhat confident,No,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript,C++;Python,MySQL,NaN,Other(s):,Other(s):,NaN,NaN,NaN,NaN,Notepad++,Linux-based,I do not use containers,NaN,NaN,No,Also Yes,What?,I don't use social media,Online,Username,2014,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was much faster,11-30 minutes,Yes,NaN,"No, I knew that Stack Overflow had a job board...",Yes,"Yes, somewhat",Not applicable - I did not use Stack Overflow ...,Industry news about technologies you're intere...,24.0,Man,No,NaN,South Asian,NaN,Appropriate in length,Easy

In [99]:
#filter used to watch a single col
df4.loc[filt1]['SocialMedia'].value_counts()

SocialMedia
WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
WeChat 微信                      5
Hello                          5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: count, dtype: int64

In [100]:
# Group a column by its country name 
country_group=df4.groupby('Country')   # divided into different group
India_Grp=country_group.get_group('India')   # Access the group 

India_Grp.head(5)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,...,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
21895,22013,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Professional degree (JD, MD, etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,2-9 employees,Academic researcher;Data scientist or machine ...,3,26,3,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,"Write code by hand (e.g., on a whiteboard);Com...",No,Financial performance or funding status of the...,"Something else changed (education, award, medi...",USD,United States dollar,1500000.0,Weekly,2000000.0,50.0,There's no schedule or spec; I work on what se...,Inadequate access to necessary tools;Meetings;...,All or almost all the time (I'm full-time remote),Home,A little below average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Developers typically have the most influence o...,...,Assembly;Bash/Shell/PowerShell;C;C++;Java;Java...,Python;Swift,Cassandra;Microsoft SQL Server;Oracle,Cassandra,Android;Arduino;Google Cloud Platform;IBM Clou...,IBM Cloud or Watson;Windows,jQuery,NaN,TensorFlow,TensorFlow,Visual Studio;Visual Studio Code,Windows,Development,Implementing our own cryptocurrency,Useful across many domains and could change ma...,Yes,Yes,No,YouTube,Online,Screen Name,NaN,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,Yes,"Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy
28080,28243,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,2-9 employees,"Developer, back-end;Developer, full-stack;Deve...",25,9,14,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles;Interview ...,Yes,Financial performance or funding status of the...,I heard about a job opportunity (from a recrui...,USD,United States dollar,2000000.0,Yearly,2000000.0,20.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Not eno...,All or almost all the time (I'm full-time remote),Office,Far above average,"Yes, because I see value in code review",NaN,NaN,NaN,...,C++;C#;Java;JavaScript;Objective-C;Python,C;C++;C#,PostgreSQL;SQLite,SQLite,Android;AWS;iOS;MacOS;Windows,Android;Linux,NaN,NaN,Node.js;Pandas;Unity 3D,Unity 3D;Unreal Engine,Android Studio;Coda;PyCharm;Visual Studio;Visu...,MacOS,I do not use containers,NaN,An irresponsible use of resources,No,Yes,No,I don't use social media,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,60+ minutes,Yes,Multiple times per day,Yes,"No, and I don't know what those are","Yes, definitely",A lot less welcome now than last year,Tech meetups or events in your area,NaN,NaN,NaN,Straight / Heterosexual,NaN,Yes,Too short,Easy
72274,72732,"I am not primarily a developer, but I write co...",No,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",NaN,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Contributed to open source software,NaN,NaN,4,20,5,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,I am actively looking for a job,More than 4 years ago,Write any code,No,Remote work options;Opportunities for professi...,I was preparing for a job search,USD,United States dollar,80000.0,Weekly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Meetings;Time ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Not sure,...,Java;Python;SQL,NaN,MongoDB;Microsoft SQL Server;MySQL;Oracle;Post...,MySQL,Android;Windows,AWS;Docker,NaN,Angular/Angular.js;React.js,NaN,NaN,Eclipse;Notepad++;PyCharm,Windows,Testing,NaN,NaN,Yes,Yes,No,WhatsApp,Neither,NaN,2017,A few times per month or weekly,Get a sense of belonging to the developer comm...,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are",Not sure,A lot less welcome now than last year,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,Yes,Too long,Easy
16703,16793,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...",Academic researcher;Data or business analyst;D...,14,14,6,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,I am actively looking for a job,1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",Yes,Office environment or company culture;Opportun...,I heard about a job opportunity (from a recrui...,INR,Indian rupee,106673250.0,Yearly,1000000.0,50.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Non-work commitme...,It's complicated,Office,Far above average,"Yes, because I see value in code review",20.0,NaN,NaN,...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Dart;G...,Bash/Shell/PowerShell;C;C++;Go;HTML/CSS;Java;J...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Angular/Angular.js;ASP.NET;Django;Drupal;Expre...,Angular/Angular.js;ASP.NET;Django;Flask;jQuery...,Apache Spark;Flutter;Hadoop;.NET;.NET Core;Nod...,Apache Spark;Hadoop;Pandas;TensorFlow;Torch/Py...,Android Studio;Atom;Eclipse;Emacs;IntelliJ;IPy...,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,Also Yes,What?,LinkedIn,Online,Handle,2009,Multiple times per day,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per week,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, definitely",Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,27.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Neither easy nor difficult
52225,52561,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"5,000 to 9,999 employees","Developer, back-end;Developer, desktop or ente...",12,11,9,Slightly satisfied,Slightly satisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",3-4 years ago,"Write any code;Write code by hand (e.g., on a ...",No,"Languages, frameworks, and other technologies ...","Something else changed (education, award, medi...",INR,Indian rupee,2000000.0,Weekly,1000000.0,40.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Distrac...,A few days each month,Office,A little above average,"Yes, because I was told to do so",2.0,"Yes, it's part of our process",Developers and management have nearly equal in...,...,C#;JavaScript,C#;JavaScript,DynamoDB;Microsoft SQL Server;SQLite,DynamoDB;Microsoft SQL Server,AWS;Docker;Linux;Windows,AWS;Docker;Linux;Windows,Angular/Angular.js;ASP.NET;Express;React.js,Angular/Angular.js;ASP.NET;Express;React.js,.NET;.NET Core;Node.js,.NET;.NET Core;Node.js,Visual Studio;Visual Studio Code,Windows,Development;Testing;Production;Outside of work...,Not at all,Useful for immutable record keeping outside of...,No,Also Yes,Yes,YouTube,Online,UserID,2009,Daily or almost daily,Find answers to specific questions;Contribute ...,1-2 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,31.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Easy

In [101]:
# Aggergated Item of stastics
country_group["ConvertedComp"].agg(['median','mean']).loc['Inda']

KeyError: 'Inda'

In [102]:
# filtering out the total % of people from each country know python
               # mini Project
def count_python_occurrences(language_series):
    return language_series.str.contains('Python').sum()

result = country_group['LanguageWorkedWith'].apply(count_python_occurrences)
result

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [103]:
def count_python_occurrences(language_series):
    return language_series.str.contains('Python').sum()

total_result = country_group['LanguageWorkedWith'].apply(count_python_occurrences)
result

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [104]:
total_Respones=df4['Country'].value_counts()

In [105]:
#concating both above output into a data frame
per_df=pd.concat([total_Respones,total_result],axis="columns",sort=False)

In [106]:
per_df

                                  count  LanguageWorkedWith
Country
United States                     20949               10083
India                              9061                3105
Germany                            5866                2451
United Kingdom                     5737                2384
Canada                             3395                1558
...                                 ...                 ...
Niger                                 1                   1
Timor-Leste                           1                   1
Chad                                  1                   0
Saint Vincent and the Grenadines      1                   0
Tonga                                 1                   0

[179 rows x 2 columns]

In [107]:
per_df["%_Know python"]=(per_df['LanguageWorkedWith']/per_df['count'])*100

In [108]:
per_df

                                  count  LanguageWorkedWith  %_Know python
Country
United States                     20949               10083      48.131176
India                              9061                3105      34.267741
Germany                            5866                2451      41.783157
United Kingdom                     5737                2384      41.554820
Canada                             3395                1558      45.891016
...                                 ...                 ...            ...
Niger                                 1                   1     100.000000
Timor-Leste                           1                   1     100.000000
Chad                                  1                   0       0.000000
Saint Vincent and the Grenadines      1                   0       0.000000
Tonga                                 1                   0       0.000000

[179 rows x 3 columns]

In [109]:
                #Data cleaning
import numpy as np
people_clean = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'], 
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

In [110]:
df_c=pd.DataFrame(people_clean)
df_c

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                     None       36
4    NaN      NaN                      NaN     None
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [111]:
# Relpace "NA" string into NaN
df_c.replace('NA',np.nan,inplace=True)
df_c.replace('Missing',np.nan,inplace=True)

In [112]:
# data cleaning 
# To finding the unique No.of enteries in a colum
df4['YearsCode'].unique()

array(['8', '9', '3', '25', '4', '15', '26', '19', '16', '43', '28', '7',
       '20', '22', '5', '12', '2', '6', '13', '11', '24', '30', '14',
       '17', '35', '18', '10', '1', '38', '21', '40', '39', nan, '29',
       '23', '42', '31', 'Less than 1 year', '34', '27', '33', '36', '37',
       '32', '45', '44', '46', '41', 'More than 50 years', '49', '50',
       '47', '48'], dtype=object)

In [113]:
df4['YearsCode'].replace('More than 50 years',0,inplace=True)

C:\Users\nasir\AppData\Local\Temp\ipykernel_11884\2665292677.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df4['YearsCode'].replace('More than 50 years',0,inplace=True)

In [114]:
df4['YearsCode'].replace('Less than 1 year', 51, inplace=True)

C:\Users\nasir\AppData\Local\Temp\ipykernel_11884\884647057.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df4['YearsCode'].replace('Less than 1 year', 51, inplace=True)

In [115]:
df4['YearsCode']=df4['YearsCode'].astype(float)

In [116]:
means=df4['YearsCode'].mean()

In [117]:
df4['YearsCode'].replace(np.nan,means,inplace=True)

C:\Users\nasir\AppData\Local\Temp\ipykernel_11884\3396043882.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df4['YearsCode'].replace(np.nan,means,inplace=True)

In [118]:
df4['YearsCode']

25833     8.000000
87353     9.000000
21895     3.000000
28080    25.000000
72274     4.000000
           ...
88873    12.381837
88874    12.381837
88879    12.381837
88880    12.381837
88881    12.381837
Name: YearsCode, Length: 88883, dtype: float64